#!/bin/zsh

__sshcrab_completions_common_fltname() {
  compadd $(/bin/bash <<EOF
  source "$CRAB_PREFIX/share/sshcrab/common"
  filter_names "$1"
EOF
)
}

__sshcrab_completions_plug_crabto() {
  __sshcrab_completions_common_fltname "$2"
}

__sshcrab_completions_plug_crabtp() {
  __sshcrab_completions_common_fltname "$2"
}


compdef __sshcrab_completions_plug_crabto crabto
compdef __sshcrab_completions_plug_crabtp crabtp
