#!/bin/bash

__sshcrab_completions_common_fltname() {
  while read -r ln; do
    if [ ! -z "$ln" ]; then
      COMPREPLY+=("$ln")
    fi
  done < <(/bin/bash <<EOF
  source "$CRAB_PREFIX/share/sshcrab/common"
  BACKEND_MODE=yes filter_names "$1"
EOF
)
}

__sshcrab_completions_plug_crabto() {
  __sshcrab_completions_common_fltname "$2"
}

__sshcrab_completions_plug_crabtp() {
  __sshcrab_completions_common_fltname "$2"
}

complete -F __sshcrab_completions_plug_crabto cbto
complete -F __sshcrab_completions_plug_crabtp cbtp
